CREATE TABLE IF NOT EXISTS b_ai_seo_tenant (
    ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(255) NOT NULL,
    CODE varchar(100) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UX_AI_SEO_TENANT_CODE (CODE)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_project (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    DOMAIN varchar(255) NOT NULL,
    NAME varchar(255) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_PROJECT_TENANT (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_task (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROJECT_ID int NOT NULL,
    TYPE varchar(100) NOT NULL,
    STATUS varchar(50) NOT NULL,
    PAYLOAD mediumtext NULL,
    LAST_ERROR text NULL,
    NEXT_RUN_AT datetime NULL,
    CREATED_AT datetime NOT NULL,
    UPDATED_AT datetime NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_TASK_SCHEDULE (STATUS, NEXT_RUN_AT),
    KEY IX_AI_SEO_TASK_PROJECT (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_api_credential (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROVIDER varchar(50) NOT NULL,
    CREDENTIALS text NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_API_CREDENTIAL_TENANT (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_report (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROJECT_ID int NOT NULL,
    TYPE varchar(50) NOT NULL,
    FORMAT varchar(10) NOT NULL,
    PATH varchar(500) NOT NULL,
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_REPORT_PROJECT (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_vector_document (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROJECT_ID int NOT NULL,
    URL varchar(500) NOT NULL,
    CONTENT mediumtext NOT NULL,
    EMBEDDING longtext NOT NULL,
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_VECTOR_PROJECT (PROJECT_ID)
);


CREATE TABLE IF NOT EXISTS b_ai_seo_subscription (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PLAN_CODE varchar(50) NOT NULL,
    STATUS varchar(30) NOT NULL,
    STARTS_AT datetime NOT NULL,
    ENDS_AT datetime NULL,
    CONTRACT_REF varchar(255) NULL,
    CREATED_AT datetime NOT NULL,
    UPDATED_AT datetime NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_SUBSCRIPTION_TENANT (TENANT_ID),
    KEY IX_AI_SEO_SUBSCRIPTION_STATUS (STATUS)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_plan_override (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    CODE varchar(100) NOT NULL,
    VALUE varchar(255) NOT NULL,
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_PLAN_OVERRIDE_TENANT (TENANT_ID)
);
