CREATE TABLE IF NOT EXISTS b_ai_seo_tenant (
    ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(255) NOT NULL,
    CODE varchar(100) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UX_AI_SEO_TENANT_CODE (CODE)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_project (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    DOMAIN varchar(255) NOT NULL,
    NAME varchar(255) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_PROJECT_TENANT (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_task (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROJECT_ID int NOT NULL,
    TYPE varchar(100) NOT NULL,
    STATUS varchar(50) NOT NULL,
    PAYLOAD mediumtext NULL,
    LAST_ERROR text NULL,
    NEXT_RUN_AT datetime NULL,
    CREATED_AT datetime NOT NULL,
    UPDATED_AT datetime NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_TASK_SCHEDULE (STATUS, NEXT_RUN_AT),
    KEY IX_AI_SEO_TASK_PROJECT (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS b_ai_seo_api_credential (
    ID int NOT NULL AUTO_INCREMENT,
    TENANT_ID int NOT NULL,
    PROVIDER varchar(50) NOT NULL,
    CREDENTIALS text NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_AT datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY IX_AI_SEO_API_CREDENTIAL_TENANT (TENANT_ID)
);
